---
name: Async Release Publish

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID"
        required: true
        default: ""
        type: string
      run_number:
        description: "Run Number"
        required: true
        default: "1"
        type: string

permissions:
  contents: write

jobs:
  publish-toolchain:
    # only actually execute on @tzarc's repo so as to not lock up QMK org's resources
    if: github.repository == 'tzarc/qmk_toolchains'

    name: Publish Toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Clone toolchains repo
        uses: actions/checkout@v4

      - name: Delete tag
        run: gh release delete latest --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          run_id: ${{ github.event.inputs.run_id }}
          name_is_regexp: true
          name: "stripped-toolchains.*"

      - name: Dump list
        run: |
          mv */*.tar.xz .
          ls -1al *.tar.xz

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            qmk_toolchain*
          tag_name: latest
